name: Pull Request
description: Propose a new change
labels: ["triage needed"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear and concise description of the changes.
    validations:
      required: true
  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - Companion UI
        - Companion Backend
        - Device Firmware
        - Shared
        - Other
    validations:
      required: true
