name: Feature Request
description: Propose a new feature
title: "[Feature]: "
type: Feature
labels: ["triage needed"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
